# Generated by Django 2.2.7 on 2019-11-28 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mariadbtest',
            old_name='name',
            new_name='ip_adress',
        ),
        migrations.AddField(
            model_name='mariadbtest',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mariadbtest',
            name='server_location',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mariadbtest',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
