# Generated by Django 2.2.7 on 2019-11-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20191128_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MariadbTest',
            new_name='servertest',
        ),
    ]
