# Generated by Django 2.2.7 on 2019-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0003_auto_20191128_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servertest',
            name='id',
        ),
        migrations.AlterField(
            model_name='servertest',
            name='ip_adress',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
